#!/usr/bin/env bash

echo "Removing dist directory..."
rm -rf dist

echo "Copying public to dist..."
cp -R ./public ./dist

echo "Compiling app.js..."
deno bundle ./src/app.js ./dist/app.bundle.js

python3 -m http.server 1234 --directory ./dist
